# Nombre del workflow
name: CI/CD Frontend

# Controla lo que se va a ejecutar (Trigger) pull, push, pull request
on:
    push:
        branches: [release, develop]
    pull_request:
        branches: [release, develop]

# Pasos a realizar
jobs:
    sistema-ventas-web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4         # Clona el repositorio actual
            - uses: actions/setup-node@v4       # Usa Node
              with:
                node-version: 22.16.0           # Versión de Node

            # Cargar la cache de node_modules, para reducir el tiempo de instalación en próximas ejecuciones
            - name: Cache node modules
              id: node-cache
              uses: actions/cache@v4
              with:
                path: sistema-ventas-web/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
            
            # Instalar las dependencias
            - name: Install dependences
              # No ejecutar si se obtuvo el node_modules de cache
              if: steps.node-cache.outputs.cache-hit != 'true'
              run: npm install

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: gerardogv/ssv:latest